### ISSUE TITLE
is proxy can be supported?

### ISSUE THREAD

**Issue by Praying** [crypto-crawler/crypto-crawler-rs#14]
Some area can't access the exchange directly, they need proxy for websocket ，so,can you provide a interface or api used for setting proxy?

**Comment by soulmachine** [comment]
@Praying For now you can use a transparent proxy such as [SSH TCP tunneling](https://www.howtogeek.com/168145/how-to-use-ssh-tunneling/), or setup a proxy on your router

**Comment by GhostLee** [comment]
#18 supported

**Comment by soulmachine** [comment]
@Praying https://github.com/crypto-crawler/crypto-crawler-rs/pull/18 has landed in the new version, try it out!

**Comment by Praying** [comment]
> 

thanks so much, I do it the same way
