### ISSUE TITLE
coinbase_pro exchange doesn't work any more

### ISSUE THREAD

**Issue by stepan-romankov** [crypto-crawler/crypto-crawler-rs#26]
https://docs.cloud.coinbase.com/exchange/reference/exchangerestapi_getproducts

> The properties base_max_size, base_min_size, max_market_funds were [removed on June 30 (https://docs.cloud.coinbase.com/exchange/docs/changelog#2022-jun-30).

src/exchanges/coinbase_pro.rs
```
fn fetch_spot_markets_raw() -> Result<Vec<SpotMarket>> {
  let txt = http_get("https://api.pro.coinbase.com/products", None)?;
  let markets = serde_json::from_str::<Vec<SpotMarket>>(&txt)?;
  Ok(markets)
}
```

**Comment by soulmachine** [comment]
Fixed in https://github.com/crypto-crawler/crypto-crawler-rs/commit/4e7be2896ef14e23fa401c997ffe65456de1e440
