### ISSUE TITLE
The development schedule of  crypto-client

### ISSUE THREAD

**Issue by foonsun** [crypto-crawler/crypto-crawler-rs#7]
Hi Soulmachine,

crypto-client is important to trade in the exchanges.

Async Client is desired.

Any schedule?

**Comment by foonsun** [comment]
Crypt-Msg-Parse only support Trade and L2orderbook,  any schedule of supporting other martket-types?

**Comment by soulmachine** [comment]
For now the `crypto-msg-parser` library supports  two message types `Trade` and `L2Event`.

What message type will you need ?

**Comment by soulmachine** [comment]
The `crypto-client` is the library to place orders, it is still under development.

There is a similar library [crypto-client](https://github.com/soulmachine/crypto-client) written in TypeScript, but it will be replace by this Rust version.

**Comment by foonsun** [comment]
> For now the `crypto-msg-parser` library supports two message types `Trade` and `L2Event`.
> 
> What message type will you need ?

The L2Event struct is incremental orderbook event. incremental---->full orderbook is better.

**Comment by foonsun** [comment]
> The `crypto-client` is the library to place orders, it is still under development.
> 
> There is a similar library [crypto-client](https://github.com/soulmachine/crypto-client) written in TypeScript, but it will be replace by this Rust version.

thanks for your great job.

**Comment by soulmachine** [comment]
Incremental orderbook messages and full snapshot messages use the same `L2Event` structure , only the `pub snapshot: bool` field is different
